name: mne-dependencies
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - mne
  - mne-qt-browser
  - autoreject
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pandas
  - nibabel
  - nilearn
  - h5py
  - pytables
  - ipython
  - ipykernel
  - jupyterlab
  - jupyterlab_widgets
  - widgetsnbextension
  - pyqt
  - pyvista
  - pyvistaqt
  - dipy
  - openmeeg
  - imageio
  - imageio-ffmpeg
  - tslearn
  - numba
  - tqdm
  - pip
  - pip:
      - mne-icalabel
      - pyxdf
      - python-adjust
      - marshmallow
      - marshmallow-dataclass
      - typing-inspect
      - spyder-kernels
